package actions

import (
	"fmt"
	"gobuff_boilerplate/models"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Currency)
// DB Table: Plural (currencies)
// Resource: Plural (Currencies)
// Path: Plural (/currencies)
// View Template Folder: Plural (/templates/currencies/)

// CurrenciesResource is the resource for the Currency model
type CurrenciesResource struct {
	buffalo.Resource
}

// List gets all Currencies. This function is mapped to the path
// GET /currencies
func (v CurrenciesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	currencies := &models.Currencies{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Currencies from the DB
	if err := q.All(currencies); err != nil {
		return err
	}

	return c.Render(200, r.JSON(currencies))
}

// Show gets the data for one Currency. This function is mapped to
// the path GET /currencies/{currency_id}
func (v CurrenciesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	// To find the Currency the parameter currency_id is used.
	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return c.Render(200, r.JSON(currency))
}

// Create adds a Currency to the DB. This function is mapped to the
// path POST /currencies
func (v CurrenciesResource) Create(c buffalo.Context) error {
	// Allocate an empty Currency
	currency := &models.Currency{}

	// Bind currency to the html form elements
	if err := c.Bind(currency); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(currency)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusCreated, r.JSON(currency))
}

// Update changes a Currency in the DB. This function is mapped to
// the path PUT /currencies/{currency_id}
func (v CurrenciesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Currency to the html form elements
	if err := c.Bind(currency); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(currency)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusOK, r.JSON(currency))
}

// Destroy deletes a Currency from the DB. This function is mapped
// to the path DELETE /currencies/{currency_id}
func (v CurrenciesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	// To find the Currency the parameter currency_id is used.
	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(currency); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.JSON(currency))
}
