package actions

import (
	"fmt"
	"gobuff_boilerplate/models"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Plan)
// DB Table: Plural (plans)
// Resource: Plural (Plans)
// Path: Plural (/plans)
// View Template Folder: Plural (/templates/plans/)

// PlansResource is the resource for the Plan model
type PlansResource struct {
	buffalo.Resource
}

// List gets all Plans. This function is mapped to the path
// GET /plans
func (v PlansResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	plans := &models.Plans{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Plans from the DB
	if err := q.All(plans); err != nil {
		return err
	}

	return c.Render(200, r.JSON(plans))
}

// Show gets the data for one Plan. This function is mapped to
// the path GET /plans/{plan_id}
func (v PlansResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Plan
	plan := &models.Plan{}

	// To find the Plan the parameter plan_id is used.
	if err := tx.Find(plan, c.Param("plan_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return c.Render(200, r.JSON(plan))
}

// Create adds a Plan to the DB. This function is mapped to the
// path POST /plans
func (v PlansResource) Create(c buffalo.Context) error {
	// Allocate an empty Plan
	plan := &models.Plan{}

	// Bind plan to the html form elements
	if err := c.Bind(plan); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(plan)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusCreated, r.JSON(plan))
}

// Update changes a Plan in the DB. This function is mapped to
// the path PUT /plans/{plan_id}
func (v PlansResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Plan
	plan := &models.Plan{}

	if err := tx.Find(plan, c.Param("plan_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Plan to the html form elements
	if err := c.Bind(plan); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(plan)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
	}

	return c.Render(http.StatusOK, r.JSON(plan))
}

// Destroy deletes a Plan from the DB. This function is mapped
// to the path DELETE /plans/{plan_id}
func (v PlansResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Plan
	plan := &models.Plan{}

	// To find the Plan the parameter plan_id is used.
	if err := tx.Find(plan, c.Param("plan_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(plan); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.JSON(plan))
}
